services:
  clickhouse:
    image: clickhouse/clickhouse-server:${CLICKHOUSE_VERSION:-23.8-alpine}
    container_name: clickhouse
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native interface
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB:-ecommerce_analytics}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-default}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-clickhouse123}
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - ecommerce-network
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-10.3.12}
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin123}
      GF_USERS_ALLOW_SIGN_UP: false
      GF_INSTALL_PLUGINS: >
        grafana-clickhouse-datasource ${GRAFANA_CLICKHOUSE_PLUGIN_VERSION:-4.8.2}
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: vertamedia-clickhouse-datasource
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - ecommerce-network
    depends_on:
      - clickhouse

volumes:
  clickhouse_data:
  grafana_data:

networks:
  ecommerce-network:
    external: true
