services:
  debezium:
    image: debezium/connect:${DEBEZIUM_IMAGE_TAG:-2.7.3.Final}
    container_name: debezium
    depends_on:
      - kafka1
      - schema-registry
    ports:
      - "8083:8083"  # Kafka Connect REST API
    environment:
      BOOTSTRAP_SERVERS: kafka1:9092
      GROUP_ID: debezium-cluster
      CONFIG_STORAGE_TOPIC: debezium_connect_configs
      OFFSET_STORAGE_TOPIC: debezium_connect_offsets
      STATUS_STORAGE_TOPIC: debezium_connect_statuses
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      ENABLE_DEBEZIUM_SCRIPTING: "true"
      ENABLE_DEBEZIUM_KC_REST_EXTENSION: "true"
      CONNECT_REST_EXTENSION_CLASSES: io.debezium.kcrestextension.DebeziumConnectRestExtension
    networks:
      - ecommerce-network

  debezium-ui:
    image: quay.io/debezium/debezium-ui:${DEBEZIUM_UI_IMAGE_TAG:-2.5}
    container_name: debezium-ui
    depends_on:
      - debezium
    ports:
      - "8085:8080"  # UI port
    environment:
      KAFKA_CONNECT_URIS: http://debezium:8083
    networks:
      - ecommerce-network
