services:
  zookeeper:
    image: confluentinc/cp-zookeeper:${ZOOKEEPER_IMAGE_TAG:-7.8.2}
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - ecommerce-network

  kafka1:
    image: confluentinc/cp-kafka:${KAFKA_IMAGE_TAG:-7.8.2}
    container_name: kafka1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - ecommerce-network

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:${REDPANDA_CONSOLE_IMAGE_TAG:-v2.8.7}
    container_name: redpanda-console
    ports:
      - "8080:8080"
    depends_on:
      - kafka1
      - schema-registry
    environment:
      # KAFKA_BROKERS: kafka1:9092
      # CONSOLE_LISTEN_PORT: 8080
      CONFIG_FILEPATH: /tmp/config/config.yaml
    volumes:
      - ./kafka/console-config.yaml:/tmp/config/config.yaml
    # command: console -config.filepath=/tmp/config/
    networks:
      - ecommerce-network

  schema-registry:
    image: confluentinc/cp-schema-registry:${KAFKA_IMAGE_TAG:-7.8.2}
    container_name: schema-registry
    depends_on:
      - kafka1
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka1:9092
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
    