services:
  ed-pyspark-jupyter:
    image: easewithdata/pyspark-jupyter-lab
    user: root
    container_name: ed-pyspark-jupyter
    ports:
      - "8888:8888"  # Jupyter Lab
      - "4040:4040"  # Spark UI
    environment:
      JUPYTER_PORT: 8888
      SPARK_UI_PORT: 4040
      GRANT_SUDO: yes
    volumes:
      - streaming_data:/data:rw
      - ./spark/data:/home/jupyter/data
      - ../../data-platform/streaming:/home/jupyter/src-streaming
      
    networks:
      - ecommerce-network

volumes:
  streaming_data:
    driver: local

networks:
  ecommerce-network:
    external: true
